package interop

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateInteropTestVectors(t *testing.T) {
	tvs, err := GenerateInteropTestVectors()
	if err != nil {
		t.Fatalf("Failed to generate test vectors: %v", err)
	}

	t.Logf("Generated %d test vectors", len(tvs.Vectors))

	for i, tv := range tvs.Vectors {
		t.Run(tv.Name, func(t *testing.T) {
			err := ValidateTestVector(&tv)
			if err != nil {
				t.Errorf("Test vector %d validation failed: %v", i, err)
			}
		})
	}
}

func TestExportImportTestVectors(t *testing.T) {
	tvs, err := GenerateInteropTestVectors()
	if err != nil {
		t.Fatalf("Failed to generate test vectors: %v", err)
	}

	tmpDir := t.TempDir()
	filename := filepath.Join(tmpDir, "test_vectors.json")

	err = tvs.ExportToFile(filename)
	if err != nil {
		t.Fatalf("Failed to export test vectors: %v", err)
	}

	_, err = os.Stat(filename)
	if err != nil {
		t.Fatalf("Exported file does not exist: %v", err)
	}

	importedTVS, err := ImportFromFile(filename)
	if err != nil {
		t.Fatalf("Failed to import test vectors: %v", err)
	}

	if importedTVS.Name != tvs.Name {
		t.Errorf("Name mismatch: expected %s, got %s", tvs.Name, importedTVS.Name)
	}

	if len(importedTVS.Vectors) != len(tvs.Vectors) {
		t.Errorf("Vector count mismatch: expected %d, got %d",
			len(tvs.Vectors), len(importedTVS.Vectors))
	}
}

func TestOneToOneJoinScenario(t *testing.T) {
	gen := NewTestVectorGenerator(2) // MLS128DHKEMP256
	tv, err := gen.GenerateOneToOneJoin()
	if err != nil {
		t.Fatalf("Failed to generate test vector: %v", err)
	}

	t.Logf("Generated test vector:")
	t.Logf("  Cipher Suite: %d", tv.CipherSuite)
	t.Logf("  Group ID: %s...", tv.GroupID[:16])
	t.Logf("  Final Epoch: %d", tv.ExpectedEpoch)
	t.Logf("  Members: %d", tv.ExpectedNumMembers)

	if tv.ExpectedEpoch != 1 {
		t.Errorf("Expected epoch 1 after join, got %d", tv.ExpectedEpoch)
	}

	if tv.ExpectedNumMembers != 2 {
		t.Errorf("Expected 2 members after join, got %d", tv.ExpectedNumMembers)
	}

	if len(tv.Welcomes) == 0 {
		t.Error("Expected at least one welcome message")
	}
}

// TestCrossImplementationRoundTrip validates that Go can process
// test vectors generated by other implementation (when available).
func TestCrossImplementationRoundTrip(t *testing.T) {
	vectorFile := os.Getenv("OPENMLS_TEST_VECTORS")
	if vectorFile == "" {
		t.Skip("Skipping cross-implementation test. Set OPENMLS_TEST_VECTORS env var to enable.")
	}

	tvs, err := ImportFromFile(vectorFile)
	if err != nil {
		t.Fatalf("Failed to import other implementation test vectors: %v", err)
	}

	t.Logf("Imported %d test vectors from other implementation", len(tvs.Vectors))

	for i, tv := range tvs.Vectors {
		t.Run(tv.Name, func(t *testing.T) {
			err := ValidateTestVector(&tv)
			if err != nil {
				t.Errorf("Test vector %d (%s) validation failed: %v", i, tv.Name, err)
			}
		})
	}
}

func TestInteropCompatibility(t *testing.T) {
	t.Log(`
Interoperability Testing
========================

To test against other implementations:

1. Generate test vectors in Go:

   tvs, err := GenerateInteropTestVectors()
   err = tvs.ExportToFile("go_test_vectors.json")

2. Import in other implementation using their test vector runner

3. Export test vectors from other implementation

4. Validate in Go:

   export OPENMLS_TEST_VECTORS=other_impl_vectors.json
   go test ./interop/... -v -run TestCrossImplementationRoundTrip

Test Vector Format
==================

See: https://github.com/mlswg/mls-implementations/blob/master/test-vectors/

Current Limitations
===================

- Only MLS128DHKEMP256 cipher suite is tested
- Basic credential type only
- Single-commit scenarios only
- External commits not yet tested
`)
}
