package interop

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateInteropTestVectors(t *testing.T) {
	// Generate test vectors
	tvs, err := GenerateInteropTestVectors()
	if err != nil {
		t.Fatalf("Failed to generate test vectors: %v", err)
	}

	t.Logf("Generated %d test vectors", len(tvs.Vectors))

	// Validate each vector
	for i, tv := range tvs.Vectors {
		t.Run(tv.Name, func(t *testing.T) {
			err := ValidateTestVector(&tv)
			if err != nil {
				t.Errorf("Test vector %d validation failed: %v", i, err)
			}
		})
	}
}

func TestExportImportTestVectors(t *testing.T) {
	// Generate test vectors
	tvs, err := GenerateInteropTestVectors()
	if err != nil {
		t.Fatalf("Failed to generate test vectors: %v", err)
	}

	// Create temporary directory
	tmpDir := t.TempDir()
	filename := filepath.Join(tmpDir, "test_vectors.json")

	// Export
	err = tvs.ExportToFile(filename)
	if err != nil {
		t.Fatalf("Failed to export test vectors: %v", err)
	}

	// Verify file exists
	_, err = os.Stat(filename)
	if err != nil {
		t.Fatalf("Exported file does not exist: %v", err)
	}

	// Import
	importedTVS, err := ImportFromFile(filename)
	if err != nil {
		t.Fatalf("Failed to import test vectors: %v", err)
	}

	// Verify imported data
	if importedTVS.Name != tvs.Name {
		t.Errorf("Name mismatch: expected %s, got %s", tvs.Name, importedTVS.Name)
	}

	if len(importedTVS.Vectors) != len(tvs.Vectors) {
		t.Errorf("Vector count mismatch: expected %d, got %d",
			len(tvs.Vectors), len(importedTVS.Vectors))
	}
}

func TestOneToOneJoinScenario(t *testing.T) {
	// This test validates the basic 1:1 join scenario
	// Scenario:
	// 1. Alice creates group
	// 2. Alice adds Bob
	// 3. Bob joins via Welcome

	gen := NewTestVectorGenerator(2) // MLS128DHKEMP256
	tv, err := gen.GenerateOneToOneJoin()
	if err != nil {
		t.Fatalf("Failed to generate test vector: %v", err)
	}

	t.Logf("Generated test vector:")
	t.Logf("  Cipher Suite: %d", tv.CipherSuite)
	t.Logf("  Group ID: %s...", tv.GroupID[:16])
	t.Logf("  Final Epoch: %d", tv.ExpectedEpoch)
	t.Logf("  Members: %d", tv.ExpectedNumMembers)

	// Basic validations
	if tv.ExpectedEpoch != 1 {
		t.Errorf("Expected epoch 1 after join, got %d", tv.ExpectedEpoch)
	}

	if tv.ExpectedNumMembers != 2 {
		t.Errorf("Expected 2 members after join, got %d", tv.ExpectedNumMembers)
	}

	// Note: Commits may be empty in simplified implementations
	// In full implementation, this would contain the actual Commit message

	if len(tv.Welcomes) == 0 {
		t.Error("Expected at least one welcome message")
	}
}

// TestCrossImplementationRoundTrip validates that Go can process
// test vectors generated by OpenMLS (when available).
// This test is skipped unless OPENMLS_TEST_VECTORS environment variable is set.
func TestCrossImplementationRoundTrip(t *testing.T) {
	// Skip unless explicitly enabled
	vectorFile := os.Getenv("OPENMLS_TEST_VECTORS")
	if vectorFile == "" {
		t.Skip("Skipping cross-implementation test. Set OPENMLS_TEST_VECTORS env var to enable.")
	}

	tvs, err := ImportFromFile(vectorFile)
	if err != nil {
		t.Fatalf("Failed to import OpenMLS test vectors: %v", err)
	}

	t.Logf("Imported %d test vectors from OpenMLS", len(tvs.Vectors))

	for i, tv := range tvs.Vectors {
		t.Run(tv.Name, func(t *testing.T) {
			err := ValidateTestVector(&tv)
			if err != nil {
				t.Errorf("Test vector %d (%s) validation failed: %v", i, tv.Name, err)
			}
		})
	}
}

// TestOpenMLSCompatibility documents the steps needed to test against OpenMLS.
func TestOpenMLSCompatibility(t *testing.T) {
	// This is a documentation test explaining how to run interoperability tests
	t.Log(`
OpenMLS Interoperability Testing
================================

To test against OpenMLS:

1. Generate test vectors in Go:
   
   tvs, err := GenerateInteropTestVectors()
   err = tvs.ExportToFile("go_test_vectors.json")

2. Import in OpenMLS using their test vector runner:
   
   cargo run --bin test_vector_runner -- --input go_test_vectors.json

3. Export test vectors from OpenMLS:
   
   cargo run --bin test_vector_generator -- --output openmls_vectors.json

4. Validate in Go:
   
   export OPENMLS_TEST_VECTORS=openmls_vectors.json
   go test ./interop/... -v -run TestCrossImplementationRoundTrip

Test Vector Format
==================

The test vectors follow the MLS Interop format defined at:
https://github.com/mlswg/mls-implementations/blob/master/test-vectors/

Each vector contains:
- CipherSuite configuration
- Group creation parameters
- Key packages
- Commits and Welcome messages
- Expected state after operations

Current Limitations
===================

- Only MLS128DHKEMP256 cipher suite is tested
- Basic credential type only
- Single-commit scenarios only
- External commits not yet tested

To implement full interoperability:
1. Complete Welcome message generation
2. Implement full UpdatePath generation
3. Add external commit support
4. Support all cipher suites defined in RFC 9420
`)
}
